### ISSUE TITLE
please check your spelling or network connection

### ISSUE THREAD

**Issue by 9199hacker** [chenjiandongx/fy#1]
Obviously,I don't have these two problems.

**Comment by chenjiandongx** [comment]
是否挂了 VPN，或者 SS 等翻墙工具了

**Comment by 9199hacker** [comment]
并没有，vpn还没开始学（我为什么要用英文问问题。。。），正常的网络连接。

**Comment by chenjiandongx** [comment]
@9199hacker git clone 一下代码，cd 到根目录去执行一下 youdao.py 文件看看吧。如果有问题就把错误打印出来看看吧

**Comment by 9199hacker** [comment]
正常情况下，在根目录下使用命令
python3 youdao.py change
会显示正常的“改变”翻译，但是在该目录下使用wd命令
wd change
会显示没有网络连接
已经设置环境变量并且联网

**Comment by chenjiandongx** [comment]
@9199hacker 
建议按以下步骤重新试一遍
1. `pip uninstall youdao-wd`
2. `cd youdao`
3. `python setup.py install`

**Note：** 请确保是在同一个 Python 环境下操作
